version: "3.8"
services:
  # JAVA SERVICES
  user-service:
    image: jwojdylak/propsi-microservices-user-service:latest  # Specify the image name and tag
    build:
      context: ./user-service
      dockerfile: ./Dockerfile
    environment:
      - SERVER_PORT=8081
    ports:
      - "8081:8081"
    networks:
      - spring-cloud-network
    restart: on-failure

  property-service:
    image: jwojdylak/propsi-microservices-property-service:latest  # Specify the image name and tag
    build:
      context: ./property-service
      dockerfile: ./Dockerfile
    environment:
      - SERVER_PORT=8082
    ports:
      - "8082:8082"
    networks:
      - spring-cloud-network
    restart: on-failure

  rental-service:
    image: jwojdylak/propsi-microservices-rental-service:latest  # Specify the image name and tag
    build:
      context: ./rental-service
      dockerfile: ./Dockerfile
    environment:
      - SERVER_PORT=8083
    ports:
      - "8083:8083"
    networks:
      - spring-cloud-network
    restart: on-failure

  payment-service:
    image: jwojdylak/propsi-microservices-payment-service:latest  # Specify the image name and tag
    build:
      context: ./payment-service
      dockerfile: ./Dockerfile
    environment:
      - SERVER_PORT=8084
    ports:
      - "8084:8084"
    networks:
      - spring-cloud-network
    restart: on-failure

  api-gateway-service:
    image: jwojdylak/propsi-microservices-api-gateway:latest
    build:
      context: ./api-gateway
      dockerfile: ./Dockerfile
    environment:
      - SERVER_PORT=8080
    ports:
      - "8080:8080"
    networks:
      - spring-cloud-network
    restart: on-failure

# NETWORK
networks:
  spring-cloud-network:
    driver: bridge
