apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-property-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-property-db
  template:
    metadata:
      labels:
        app: postgres-property-db
    spec:
      containers:
        - name: postgres-property-db
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: property_db
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_PASSWORD
              value: pass
          resources:
            requests:
              memory: "400Mi"
              cpu: "0.5"
            limits:
              memory: "400Mi"
              cpu: "0.5"

          volumeMounts:
            - name: postgres-property-volume
              mountPath: /var/lib/postgresql/property-data
      volumes:
        - name: postgres-property-volume
          persistentVolumeClaim:
            claimName: postgres-property-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-property-db-service
spec:
  selector:
    app: postgres-property-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP