apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-user-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-user-db
  template:
    metadata:
      labels:
        app: postgres-user-db
    spec:
      containers:
        - name: postgres-user-db
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: user_db
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_PASSWORD
              value: pass
          volumeMounts:
            - name: postgres-user-volume
              mountPath: /var/lib/postgresql/user-data
          resources:
            requests:
              memory: "600Mi"
              cpu: "1"
            limits:
              memory: "600Mi"
              cpu: "2"
      volumes:
        - name: postgres-user-volume
          persistentVolumeClaim:
            claimName: postgres-user-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-user-db-service
spec:
  selector:
    app: postgres-user-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP