apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-service
  labels:
    app.kubernetes.io/name: api-gateway-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: api-gateway-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: api-gateway-service
    spec:
      containers:
        - name: api-gateway-service
          image: jwojdylak/propsi-microservices-api-gateway:latest
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: "JAVA_OPTS"
              value: "-Xmx75M"
          resources:
            requests:
              memory: "400Mi"
              cpu: "0.7"
            limits:
              memory: "400Mi"
              cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: api-gateway-service
  name: api-gateway-service
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: api-gateway-service
  type: LoadBalancer

---
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: api-gateway-service
  labels:
    app.kubernetes.io/name: api-gateway-service
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: api-gateway-service
  endpoints:
    - port: http
      path: /api-gateway/actuator/prometheus
      interval: 30s