apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  labels:
    app.kubernetes.io/name: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: payment-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: payment-service
    spec:
      containers:
        - name: payment-service
          image: jwojdylak/propsi-microservices-payment-service:latest
          imagePullPolicy: "Always"
          ports:
            - name: http
              containerPort: 8084
          env:
            - name: SERVER_PORT
              value: "8084"
            - name: "JAVA_OPTS"
              value: "-Xmx75M"
          resources:
            requests:
              memory: "600Mi"
              cpu: "0.5"
            limits:
              memory: "600Mi"
              cpu: "0.6"

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: payment-service
  name: payment-service
spec:
  ports:
    - name: http
      port: 8084
      protocol: TCP
      targetPort: 8084
  selector:
    app.kubernetes.io/name: payment-service
  type: ClusterIP

---
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: payment-service
  labels:
    app.kubernetes.io/name: payment-service
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: payment-service
  endpoints:
    - port: http
      path: /payment-service/actuator/prometheus
      interval: 30s