apiVersion: apps/v1
kind: Deployment
metadata:
  name: property-service
  labels:
    app: property-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: property-service
  template:
    metadata:
      labels:
        app: property-service
    spec:
      containers:
        - name: property-service
          image: jwojdylak/propsi-microservices-property-service:latest
          ports:
            - containerPort: 8082
          env:
            - name: SERVER_PORT
              value: "8082"
            - name: "JAVA_OPTS"
              value: "-Xmx75M"
          resources:
            requests:
              memory: "900Mi"
              cpu: "200m"
            limits:
              memory: "900Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: property-service
  name: property-service
spec:
  ports:
    - name: 8082-8082
      port: 8082
      protocol: TCP
      targetPort: 8082
  selector:
    app: property-service
  type: ClusterIP