apiVersion: apps/v1
kind: Deployment
metadata:
  name: property-service
  labels:
    app.kubernetes.io/name: property-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: property-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: property-service
    spec:
      containers:
        - name: property-service
          image: jwojdylak/propsi-microservices-property-service:latest
          imagePullPolicy: "Always"
          ports:
            - name: http
              containerPort: 8082
          env:
            - name: SERVER_PORT
              value: "8082"
            - name: "JAVA_OPTS"
              value: "-Xmx75M"
          resources:
            requests:
              memory: "600Mi"
              cpu: "0.5"
            limits:
              memory: "600Mi"
              cpu: "0.6"

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: property-service
  name: property-service
spec:
  ports:
    - name: http
      port: 8082
      protocol: TCP
      targetPort: 8082
  selector:
    app.kubernetes.io/name: property-service
  type: ClusterIP

---
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: property-service
  labels:
    app.kubernetes.io/name: property-service
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: property-service
  endpoints:
    - port: http
      path: /property-service/actuator/prometheus
      interval: 30s
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: property-service
  namespace: default
spec:
  maxReplicas: 1
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 70
          type: Utilization
      type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: property-service
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Pods
          value: 1
          periodSeconds: 30
    scaleDown:
      stabilizationWindowSeconds: 180
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60