apiVersion: apps/v1
kind: Deployment
metadata:
  name: property-service
  labels:
    app.kubernetes.io/name: property-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: property-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: property-service
    spec:
      containers:
        - name: property-service
          image: jwojdylak/propsi-microservices-property-service:latest
          ports:
            - name: http
              containerPort: 8082
          env:
            - name: SERVER_PORT
              value: "8082"
            - name: "JAVA_OPTS"
              value: "-Xmx75M"
          resources:
            requests:
              memory: "1024Mi"
              cpu: "200m"
            limits:
              memory: "1024Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: property-service
  name: property-service
spec:
  ports:
    - name: http
      port: 8082
      protocol: TCP
      targetPort: 8082
  selector:
    app.kubernetes.io/name: property-service
  type: ClusterIP

---
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: property-service
  labels:
    app.kubernetes.io/name: property-service
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: property-service
  endpoints:
    - port: http
      path: /property-service/actuator/prometheus
      interval: 30s