apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app.kubernetes.io/name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: user-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: user-service
    spec:
      containers:
        - name: user-service
          image: jwojdylak/propsi-microservices-user-service:latest
          ports:
            - name: http
              containerPort: 8081
          env:
            - name: SERVER_PORT
              value: "8081"
            - name: "JAVA_OPTS"
              value: "-Xmx75M"
          resources:
            requests:
              memory: "1024Mi"
              cpu: "200m"
            limits:
              memory: "1024Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: user-service
  name: user-service
spec:
  ports:
    - name: http
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app.kubernetes.io/name: user-service
  type: ClusterIP

---
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: user-service
  labels:
    app.kubernetes.io/name: user-service
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: user-service
  endpoints:
    - port: http
      path: /user-service/actuator/prometheus
      interval: 30s

#kubectl create deployment demo --image=jwojdylak/propsi-microservices-user-service:LATEST --dry-run -o=yaml > deployment.yaml
#echo --- >> deployment.yaml
#kubectl create service clusterip demo --tcp=8081:8081 --dry-run -o=yaml >> deployment.yaml